/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#6d0010",
        "secondary-container": "#ff6b6b",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-primary-fixed-variant": "#93000d",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed-dim": "#b4c5ff",
        "error": "#ba1a1a",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "on-secondary-fixed": "#410006",
        "surface-tint": "#bb171c",
        "outline-variant": "#e4beb9",
        "tertiary-container": "#316bf3",
        "on-surface-variant": "#5b403d",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#00174b",
        "on-error-container": "#93000a",
        "tertiary": "#0051d5",
        "on-tertiary-container": "#fefcff",
        "surface": "#f8f9fa",
        "inverse-primary": "#ffb4ac",
        "secondary-fixed": "#ffdad8",
        "secondary-fixed-dim": "#ffb3b0",
        "tertiary-fixed": "#dbe1ff",
        "primary": "#b7131a",
        "on-secondary-fixed-variant": "#8c1520",
        "inverse-on-surface": "#f0f1f2",
        "background": "#f8f9fa",
        "on-secondary": "#ffffff",
        "primary-container": "#db322f",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-background": "#191c1d",
        "on-primary-container": "#fffbff",
        "outline": "#906f6c",
        "on-primary-fixed": "#410002",
        "surface-container-low": "#f3f4f5",
        "surface-bright": "#f8f9fa",
        "primary-fixed-dim": "#ffb4ac",
        "surface-variant": "#e1e3e4",
        "on-primary": "#ffffff",
        "secondary": "#ae2f34",
        "on-surface": "#191c1d",
        "primary-fixed": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
