ALTER TABLE users
ADD COLUMN IF NOT EXISTS whatsapp_phone VARCHAR(20);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS whatsapp_opt_in BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS whatsapp_opt_in_at TIMESTAMPTZ;